# DecisionTreeClassifier { #sklearn.tree.DecisionTreeClassifier }

`tree.DecisionTreeClassifier(self, *, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0, monotonic_cst=None)`

A decision tree classifier.

Read more in the :ref:`User Guide <tree>`.

## Parameters

| Name                       | Type                                    | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Default   |
|----------------------------|-----------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `criterion`                | (gini, entropy, log_loss)               | The function to measure the quality of a split. Supported criteria are "gini" for the Gini impurity and "log_loss" and "entropy" both for the Shannon information gain, see :ref:`tree_mathematical_formulation`.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | `"gini"`  |
| `splitter`                 | (best, random)                          | The strategy used to choose the split at each node. Supported strategies are "best" to choose the best split and "random" to choose the best random split.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | `"best"`  |
| `max_depth`                | int                                     | The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | `None`    |
| `min_samples_split`        | int or float                            | The minimum number of samples required to split an internal node:  - If int, then consider `min_samples_split` as the minimum number. - If float, then `min_samples_split` is a fraction and   `ceil(min_samples_split * n_samples)` are the minimum   number of samples for each split.  .. versionchanged:: 0.18    Added float values for fractions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | `2`       |
| `min_samples_leaf`         | int or float                            | The minimum number of samples required to be at a leaf node. A split point at any depth will only be considered if it leaves at least ``min_samples_leaf`` training samples in each of the left and right branches.  This may have the effect of smoothing the model, especially in regression.  - If int, then consider `min_samples_leaf` as the minimum number. - If float, then `min_samples_leaf` is a fraction and   `ceil(min_samples_leaf * n_samples)` are the minimum   number of samples for each node.  .. versionchanged:: 0.18    Added float values for fractions.                                                                                                                                                                                                                                                                                                                                                 | `1`       |
| `min_weight_fraction_leaf` | float                                   | The minimum weighted fraction of the sum total of weights (of all the input samples) required to be at a leaf node. Samples have equal weight when sample_weight is not provided.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | `0.0`     |
| `max_features`             | (int, float or {sqrt, log2})            | The number of features to consider when looking for the best split:      - If int, then consider `max_features` features at each split.     - If float, then `max_features` is a fraction and       `max(1, int(max_features * n_features_in_))` features are considered at       each split.     - If "sqrt", then `max_features=sqrt(n_features)`.     - If "log2", then `max_features=log2(n_features)`.     - If None, then `max_features=n_features`.  Note: the search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.                                                                                                                                                                                                                                                                           | `None`    |
| `random_state`             | int, RandomState instance or None       | Controls the randomness of the estimator. The features are always randomly permuted at each split, even if ``splitter`` is set to ``"best"``. When ``max_features < n_features``, the algorithm will select ``max_features`` at random at each split before finding the best split among them. But the best found split may vary across different runs, even if ``max_features=n_features``. That is the case, if the improvement of the criterion is identical for several splits and one split has to be selected at random. To obtain a deterministic behaviour during fitting, ``random_state`` has to be fixed to an integer. See :term:`Glossary <random_state>` for details.                                                                                                                                                                                                                                               | `None`    |
| `max_leaf_nodes`           | int                                     | Grow a tree with ``max_leaf_nodes`` in best-first fashion. Best nodes are defined as relative reduction in impurity. If None then unlimited number of leaf nodes.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | `None`    |
| `min_impurity_decrease`    | float                                   | A node will be split if this split induces a decrease of the impurity greater than or equal to this value.  The weighted impurity decrease equation is the following::      N_t / N * (impurity - N_t_R / N_t * right_impurity                         - N_t_L / N_t * left_impurity)  where ``N`` is the total number of samples, ``N_t`` is the number of samples at the current node, ``N_t_L`` is the number of samples in the left child, and ``N_t_R`` is the number of samples in the right child.  ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum, if ``sample_weight`` is passed.  .. versionadded:: 0.19                                                                                                                                                                                                                                                                                         | `0.0`     |
| `class_weight`             | dict, list of dict or "balanced"        | Weights associated with classes in the form ``{class_label: weight}``. If None, all classes are supposed to have weight one. For multi-output problems, a list of dicts can be provided in the same order as the columns of y.  Note that for multioutput (including multilabel) weights should be defined for each class of every column in its own dict. For example, for four-class multilabel classification weights should be [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of [{1:1}, {2:5}, {3:1}, {4:1}].  The "balanced" mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as ``n_samples / (n_classes * np.bincount(y))``  For multi-output, the weights of each column of y will be multiplied.  Note that these weights will be multiplied with sample_weight (passed through the fit method) if sample_weight is specified. | `None`    |
| `ccp_alpha`                | non-negative float                      | Complexity parameter used for Minimal Cost-Complexity Pruning. The subtree with the largest cost complexity that is smaller than ``ccp_alpha`` will be chosen. By default, no pruning is performed. See :ref:`minimal_cost_complexity_pruning` for details.  .. versionadded:: 0.22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | `0.0`     |
| `monotonic_cst`            | array-like of int of shape (n_features) | Indicates the monotonicity constraint to enforce on each feature.   - 1: monotonic increase   - 0: no constraint   - -1: monotonic decrease  If monotonic_cst is None, no constraints are applied.  Monotonicity constraints are not supported for:   - multiclass classifications (i.e. when `n_classes > 2`),   - multioutput classifications (i.e. when `n_outputs_ > 1`),   - classifications trained on data with missing values.  The constraints hold over the probability of the positive class.  Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.  .. versionadded:: 1.4                                                                                                                                                                                                                                                                                                                                         | `None`    |

## Attributes

| Name                 | Type                                             | Description                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|----------------------|--------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| classes_             | ndarray of shape (n_classes,) or list of ndarray | The classes labels (single output problem), or a list of arrays of class labels (multi-output problem).                                                                                                                                                                                                                                                                                                                                              |
| feature_importances_ | ndarray of shape (n_features,)                   | The impurity-based feature importances. The higher, the more important the feature. The importance of a feature is computed as the (normalized) total reduction of the criterion brought by that feature.  It is also known as the Gini importance [4]_.  Warning: impurity-based feature importances can be misleading for high cardinality features (many unique values). See :func:`sklearn.inspection.permutation_importance` as an alternative. |
| max_features_        | int                                              | The inferred value of max_features.                                                                                                                                                                                                                                                                                                                                                                                                                  |
| n_classes_           | int or list of int                               | The number of classes (for single output problems), or a list containing the number of classes for each output (for multi-output problems).                                                                                                                                                                                                                                                                                                          |
| n_features_in_       | int                                              | Number of features seen during :term:`fit`.  .. versionadded:: 0.24                                                                                                                                                                                                                                                                                                                                                                                  |
| feature_names_in_    | ndarray of shape (`n_features_in_`,)             | Names of features seen during :term:`fit`. Defined only when `X` has feature names that are all strings.  .. versionadded:: 1.0                                                                                                                                                                                                                                                                                                                      |
| n_outputs_           | int                                              | The number of outputs when ``fit`` is performed.                                                                                                                                                                                                                                                                                                                                                                                                     |
| tree_                | Tree instance                                    | The underlying Tree object. Please refer to ``help(sklearn.tree._tree.Tree)`` for attributes of Tree object and :ref:`sphx_glr_auto_examples_tree_plot_unveil_tree_structure.py` for basic usage of these attributes.                                                                                                                                                                                                                                |

## See Also

DecisionTreeRegressor : A decision tree regressor.

## Notes

The default values for the parameters controlling the size of the trees
(e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
unpruned trees which can potentially be very large on some data sets. To
reduce memory consumption, the complexity and size of the trees should be
controlled by setting those parameter values.

The :meth:`predict` method operates using the :func:`numpy.argmax`
function on the outputs of :meth:`predict_proba`. This means that in
case the highest predicted probabilities are tied, the classifier will
predict the tied class with the lowest index in :term:`classes_`.

## References


.. [1] https://en.wikipedia.org/wiki/Decision_tree_learning

.. [2] L. Breiman, J. Friedman, R. Olshen, and C. Stone, "Classification
       and Regression Trees", Wadsworth, Belmont, CA, 1984.

.. [3] T. Hastie, R. Tibshirani and J. Friedman. "Elements of Statistical
       Learning", Springer, 2009.

.. [4] L. Breiman, and A. Cutler, "Random Forests",
       https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm

## Examples

```python
>>> from sklearn.datasets import load_iris
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.tree import DecisionTreeClassifier
>>> clf = DecisionTreeClassifier(random_state=0)
>>> iris = load_iris()
>>> cross_val_score(clf, iris.data, iris.target, cv=10)
...
...
array([ 1.     ,  0.93...,  0.86...,  0.93...,  0.93...,
        0.93...,  0.93...,  1.     ,  0.93...,  1.      ])
```

## Methods

| Name | Description |
| --- | --- |
| [fit](#sklearn.tree.DecisionTreeClassifier.fit) | Build a decision tree classifier from the training set (X, y). |
| [predict_log_proba](#sklearn.tree.DecisionTreeClassifier.predict_log_proba) | Predict class log-probabilities of the input samples X. |
| [predict_proba](#sklearn.tree.DecisionTreeClassifier.predict_proba) | Predict class probabilities of the input samples X. |

### fit { #sklearn.tree.DecisionTreeClassifier.fit }

`tree.DecisionTreeClassifier.fit(X, y, sample_weight=None, check_input=True)`

Build a decision tree classifier from the training set (X, y).

#### Parameters

| Name            | Type                                                       | Description                                                                                                                                                                                                                                                                                               | Default      |
|-----------------|------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|
| `X`             | array-like, sparse matrix                                  | The training input samples. Internally, it will be converted to ``dtype=np.float32`` and if a sparse matrix is provided to a sparse ``csc_matrix``.                                                                                                                                                       | `array-like` |
| `y`             | array-like of shape (n_samples,) or (n_samples, n_outputs) | The target values (class labels) as integers or strings.                                                                                                                                                                                                                                                  | _required_   |
| `sample_weight` | array-like of shape (n_samples,)                           | Sample weights. If None, then samples are equally weighted. Splits that would create child nodes with net zero or negative weight are ignored while searching for a split in each node. Splits are also ignored if they would result in any single class carrying a negative weight in either child node. | `None`       |
| `check_input`   | bool                                                       | Allow to bypass several input checking. Don't use this parameter unless you know what you're doing.                                                                                                                                                                                                       | `True`       |

#### Returns

| Type                   | Description       |
|------------------------|-------------------|
| DecisionTreeClassifier | Fitted estimator. |

### predict_log_proba { #sklearn.tree.DecisionTreeClassifier.predict_log_proba }

`tree.DecisionTreeClassifier.predict_log_proba(X)`

Predict class log-probabilities of the input samples X.

#### Parameters

| Name   | Type                      | Description                                                                                                                                | Default      |
|--------|---------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------|
| `X`    | array-like, sparse matrix | The input samples. Internally, it will be converted to ``dtype=np.float32`` and if a sparse matrix is provided to a sparse ``csr_matrix``. | `array-like` |

#### Returns

| Type                                                                                                  | Description                                                                                                                       |
|-------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| ndarray of shape (n_samples, n_classes) or list of n_outputs             such arrays if n_outputs > 1 | The class log-probabilities of the input samples. The order of the classes corresponds to that in the attribute :term:`classes_`. |

### predict_proba { #sklearn.tree.DecisionTreeClassifier.predict_proba }

`tree.DecisionTreeClassifier.predict_proba(X, check_input=True)`

Predict class probabilities of the input samples X.

The predicted class probability is the fraction of samples of the same
class in a leaf.

#### Parameters

| Name          | Type                      | Description                                                                                                                                | Default      |
|---------------|---------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------|
| `X`           | array-like, sparse matrix | The input samples. Internally, it will be converted to ``dtype=np.float32`` and if a sparse matrix is provided to a sparse ``csr_matrix``. | `array-like` |
| `check_input` | bool                      | Allow to bypass several input checking. Don't use this parameter unless you know what you're doing.                                        | `True`       |

#### Returns

| Type                                                                                                  | Description                                                                                                                   |
|-------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| ndarray of shape (n_samples, n_classes) or list of n_outputs             such arrays if n_outputs > 1 | The class probabilities of the input samples. The order of the classes corresponds to that in the attribute :term:`classes_`. |